---
# Titanic dataset
---

In [2]:
import pandas as pd

In [4]:
# 1. Load the dataset and display the first 10 rows. 
titanic = pd.read_csv(r"C:\Users\sanjn\OneDrive\Desktop\titanic.csv")
titanic.head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False

In [5]:
# 2. Show the shape, column names, and data types. 
print(titanic.info())
print("-"*50)
print(f"Shape : {titanic.shape} \nColumns : {titanic.columns}\n Datatypes : {titanic.dtypes}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    object
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(7)
memory usage: 92.4+ KB
None
--------------------------------------------------
Shape : (891, 15)
Columns : Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')
 Datatypes : survived         int64
pclass           int64
sex             object
age            float64
sibsp            int64
parch            int64
fare           float64
embarked        object
class           object
who             object
adult_male        bool
deck            object
embark_town     object
alive           object
alone             bool
dtype: object

In [6]:
# 3. Find the number of passengers who survived and who did not survive.
survived_data = titanic['survived'].value_counts()
survived_data

survived
0    549
1    342
Name: count, dtype: int64

In [7]:
print("Survived count : ", survived_data.values[1])
print("Not Survived count : ", survived_data.values[0])

Survived count :  342
Not Survived count :  549

In [8]:
# 4. Count how many female passengers travelled in 1st class. 
f_1_class = titanic[ (titanic['sex'] == 'female') & (titanic['pclass'] == 1) ]['survived'].count()
print("Count of females travelling in 1st class: ", f_1_class)

Count of females travelling in 1st class:  94

In [9]:
# 5. Count how many female passengers survived and were under 30 years old. 
f_s_30 = titanic[ (titanic['sex'] == 'female') & (titanic['age'] < 30) & (titanic['survived'] == 1) ]['survived'].count()
print("Count of female passengers survived and were under 30 years old: ", f_s_30)

Count of female passengers survived and were under 30 years old:  105

In [10]:
# 6. Count how many male passengers survived and were over 40 years old.
m_s_30 = titanic[ (titanic['sex'] == 'male') & (titanic['age'] > 40) & (titanic['survived'] == 1) ]['survived'].count()
print("Count of male passengers survived and were over 40 years old: ", m_s_30)

Count of male passengers survived and were over 40 years old:  18

In [11]:
# 7. Show the count of passengers in each class. 
pclasses = titanic['pclass'].value_counts()
pclasses

pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [12]:
print("Class First count: ", pclasses.values[1])
print("Class Second count: ", pclasses.values[2])
print("Class Third count: ", pclasses.values[0])

Class First count:  216
Class Second count:  184
Class Third count:  491

In [13]:
# 8. Show the survival count for each class.
pclasses_sur = titanic[(titanic['survived'] == 1)]['pclass'].value_counts()
pclasses_sur

pclass
1    136
3    119
2     87
Name: count, dtype: int64

In [14]:
# 9. Show the average age of passengers for each class.
print("First class: ", titanic[ titanic['pclass'] == 1]['age'].mean())
print("Second class: ", titanic[ titanic['pclass'] == 2]['age'].mean())
print("Third class: ", titanic[ titanic['pclass'] == 3]['age'].mean())

First class:  38.233440860215055
Second class:  29.87763005780347
Third class:  25.14061971830986

In [15]:
# 10. Replace missing values in the age column with its median. 
titanic.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [16]:
median = titanic['age'].median()
print("median: ", median)
titanic['age'].fillna(median, inplace=True)
titanic.isnull().sum()

median:  28.0

C:\Users\sanjn\AppData\Local\Temp\ipykernel_12304\4148490387.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  titanic['age'].fillna(median, inplace=True)

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [17]:
# 11. Encode the sex column as numbers (male=1, female=0).
titanic["sex_encode"] = titanic['sex'].map({"male" : 1, "female" : 0})

In [18]:
titanic.head(5)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,sex_encode
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1

In [19]:
# 12. Drop the columns deck and embark_town.
titanic.drop(columns=['deck','embark_town'], inplace=True)
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,alive,alone,sex_encode
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,no,False,1
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,yes,False,0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,yes,True,0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,yes,False,0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,no,True,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,no,True,1
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,yes,True,0
888,0,3,female,28.0,1,2,23.4500,S,Third,woman,False,no,False,0
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,yes,True,1
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,no,True,1

In [20]:
# 13. Find the mean fare paid by survivors vs non-survivors. 
print("Mean fare of survived passengers: ",titanic[titanic['survived'] == 1]['fare'].mean())
print("Mean fare of not survived passengers: ",titanic[titanic['survived'] == 0]['fare'].mean())

Mean fare of survived passengers:  48.39540760233918
Mean fare of not survived passengers:  22.117886885245902

In [21]:
# 14. Create a new column fare_per_person = fare / number of siblings + spouses + 1. 
titanic['fare_per_person'] = titanic['fare'] / (titanic['sibsp'] + 1)
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,alive,alone,sex_encode,fare_per_person
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,no,False,1,3.62500
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,yes,False,0,35.64165
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,yes,True,0,7.92500
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,yes,False,0,26.55000
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,no,True,1,8.05000

In [22]:
# 15. Show the top 10 passengers with the highest fare_per_person.
titanic['fare_per_person'].sort_values(ascending=False).head(10)

737    512.3292
258    512.3292
679    512.3292
299    247.5208
118    247.5208
716    227.5250
380    227.5250
557    227.5250
527    221.7792
377    211.5000
Name: fare_per_person, dtype: float64